name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Regenerate web directory
        run: |
          rm -rf web
          flutter create --platforms web .

      - name: Build Flutter Web with correct base href
        run: flutter build web --base-href /flutter/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
